// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyQdVYudbDJKn1pv5M52pJ671yaWaltGQ',
    appId: '1:751779526034:web:0689fbd5795ab92b723d4b',
    messagingSenderId: '751779526034',
    projectId: 'universidades-7390e',
    authDomain: 'universidades-7390e.firebaseapp.com',
    storageBucket: 'universidades-7390e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzS2_L8T0quNrwpGv2QqgTit1m4y0Yv5k',
    appId: '1:751779526034:android:16e4a4ea2512641f723d4b',
    messagingSenderId: '751779526034',
    projectId: 'universidades-7390e',
    storageBucket: 'universidades-7390e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdismSR87K9YYxc6BPbH_axwjnee6ZfVU',
    appId: '1:751779526034:ios:3b466c5b76559d83723d4b',
    messagingSenderId: '751779526034',
    projectId: 'universidades-7390e',
    storageBucket: 'universidades-7390e.firebasestorage.app',
    iosBundleId: 'com.example.desarolloMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdismSR87K9YYxc6BPbH_axwjnee6ZfVU',
    appId: '1:751779526034:ios:3b466c5b76559d83723d4b',
    messagingSenderId: '751779526034',
    projectId: 'universidades-7390e',
    storageBucket: 'universidades-7390e.firebasestorage.app',
    iosBundleId: 'com.example.desarolloMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyQdVYudbDJKn1pv5M52pJ671yaWaltGQ',
    appId: '1:751779526034:web:bccc609d38819db8723d4b',
    messagingSenderId: '751779526034',
    projectId: 'universidades-7390e',
    authDomain: 'universidades-7390e.firebaseapp.com',
    storageBucket: 'universidades-7390e.firebasestorage.app',
  );
}
